#ifndef _FTRANS_H
#define _FTRANS_H

#define FTRANS_PORT 7801
#define FTRANS_SEND_BUF_SIZE 1024
#define FTRANS_RECV_BUF_SIZE 1024

#define FTRANS_UPLOAD_PATH "./uploads"
#define FTRANS_UPLOAD_MOD (0770)

#define FTRANS_TCP_LISTENBACKLOG 5

#endif //_FTRANS_H
